### ISSUE TITLE
Continuação deste projeto com as funcionalidades possíveis 

### ISSUE THREAD

**Issue by LipzyLipzy** [giampaulo/pastaarquivos#1]
Boa tarde Giampaulo. 
Eu tenho seguido o Mapos, já a muito tempo e tenho actualizado sempre mas uma das ferramentas que me agradou muito não foi aprovada e tenho eu tentado aplicar. 

Como o amigo deixou está a trabalhar mas não consigo por exemplo ver os PDFs sem ter de fazer download. 

Será que pode dar uma ajuda?

Seria muito bom continuar com este projeto não digo no mapos para não ter duplicados mas sim só está pasta onde está todo o sistema para gerir os ficheiros. 

Obrigado

**Comment by giampaulo** [comment]
Cara. É possível fazer o preview do pdf no próprio navegador. Inclusive de arquivos PNG, jpg e etc. se vc der uma boa olhada no código vc localiza essa funcionalidade. Não estou com muito tempo pra dar suporte para esse esquema no momento. Mas poucas pesquisas na internet certamente já solucionam teu problema.

**Comment by LipzyLipzy** [comment]
Sabe qual é o ficheiro onde tenho de editar?

**Comment by giampaulo** [comment]
Imagino que seja na dialog.php


Att

Giampaulo Hanauer

giampaulo@gmail.com
Em 24 de jul de 2020 17:09 -0300, LipzyLipzy <notifications@github.com> escreveu:

**Comment by LipzyLipzy** [comment]
Não está fácil! 
Estive a verificar mas não percebi como o fazer. 
Eu não sou programador logo também não ajuda. 
Também tive a pesquisar mas o que encontrei era em versões antigas e foi alterando. 

Quando tiver um tempo se poder ajudar agradecia muito. 

Obrigado, abraço

**Comment by giampaulo** [comment]
Busque na internet sobre responsive file manager. Já existe um projeto pronto e diversos em andamento. Sinto muito mas tão logo não consigo ajudar.


Att

Giampaulo Hanauer

giampaulo@gmail.com
Em 25 de jul de 2020 05:24 -0300, LipzyLipzy <notifications@github.com> escreveu:

**Comment by LipzyLipzy** [comment]
Ok obrigado, vou tentar encontrar. Abraço

**Comment by LipzyLipzy** [comment]
Olá giampaulo,
Não cheguei a conseguir, mas não quis estar a insistir. 
Será que tem agora um tempinho para ajudar? 

Obrigado

**Comment by giampaulo** [comment]
Da uma olhada no meu repositório. Lá tem a pasta que vc precisa editar como nunca mais mexi nisso o projeto foi deixado de lado. Mas a princípio é só trocar a pasta arquivos por essa pasta do meu repositório aí tb não lembro se alterava alguma coisa a mais mas acho que não.


Att

Giampaulo Hanauer

giampaulo@gmail.com
Em 4 de nov. de 2020 21:07 -0300, LipzyLipzy <notifications@github.com> escreveu:
